"""OTel Collector sidecar config rendering.

Produces the YAML config consumed by every sidecar in the project, in a
form suitable for two delivery mechanisms: a file mount on fixed (via
compose `configs:`) and an embedded env-var literal on elastic (via the
otelcol `env:` config provider).

Only the exporter destination differs by env: dev/test → debug exporter
writing to sidecar stdout; stage/prod → otlphttp targeting the project's
observability backend with API-key auth. See
doctrine/infrastructure/specifics/telemetry_infra.md § Per-Env Exporter
Configuration.
"""

from __future__ import annotations


def render_otelcol_config(env: str) -> str:
    """Return the OTel Collector YAML config for ``env`` as a string.

    Determinism: keys are emitted in a fixed order; no map iteration
    randomness reaches the output.
    """
    use_debug = env in ("dev", "test")
    exporter_name = "debug" if use_debug else "otlphttp"

    if use_debug:
        exporter_block = "  debug:\n    verbosity: detailed\n"
    else:
        # The ${env:...} substitutions are otelcol's own — they must appear
        # in the output verbatim. Python only interpolates {name} (single
        # braces) inside f-strings, not ${...}, so these survive.
        exporter_block = (
            "  otlphttp:\n"
            "    endpoint: ${env:OBSERVABILITY_BACKEND_URL}\n"
            "    headers:\n"
            "      authorization: ${env:TELEMETRY_API_KEY}\n"
        )

    return (
        "# Generated by `docex compile`. Do not edit by hand.\n"
        f"# env: {env}\n"
        "receivers:\n"
        "  otlp:\n"
        "    protocols:\n"
        "      http:\n"
        "        endpoint: 127.0.0.1:4318\n"
        "processors:\n"
        "  batch: {}\n"
        "exporters:\n"
        f"{exporter_block}"
        "extensions:\n"
        "  health_check:\n"
        "    endpoint: 127.0.0.1:13133\n"
        "service:\n"
        "  extensions: [health_check]\n"
        "  pipelines:\n"
        f"    traces:  {{ receivers: [otlp], processors: [batch], exporters: [{exporter_name}] }}\n"
        f"    metrics: {{ receivers: [otlp], processors: [batch], exporters: [{exporter_name}] }}\n"
        f"    logs:    {{ receivers: [otlp], processors: [batch], exporters: [{exporter_name}] }}\n"
    )
