"""Clock schedule-table rendering and delivery. Mod 115.

Modelled on :mod:`docex.emit.otelcol`: pure functions, strings out, no I/O.
Two artifacts with two different jobs, plus the one seam through which both
foundations deliver the table to a running clock.

See ``doctrine/infrastructure/specifics/clock.md`` § How the schedule reaches
the container.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover - typing only
    from docex.cicl.compile import CompiledEnv, CompiledService


_HEADER = "# Generated by `docex compile`. Do not edit by hand.\n"

# The one variable through which a clock receives its schedule table, on BOTH
# foundations. Its value is the LITERAL rendered YAML, not a path to a file.
# This module is the source of truth for the name; `cicl/validate.py`
# duplicates the literal into `_RESERVED_CORE_ENV_KEYS` so rule 20 rejects a
# project that declares it in its own `env:` / `secrets:` / `config:` blocks.
SCHEDULES_ENV_KEY = "DOCEX_SCHEDULES_YAML"


def _yaml_quote(value: str) -> str:
    """Double-quote a cron expression for YAML.

    Cron expressions start with digits or ``*`` and contain spaces and
    ``*``/``?``/``,`` — all of which are either ambiguous or outright illegal
    as plain scalars in some position, so every value is quoted rather than
    quoted conditionally. Backslash and double-quote are escaped; nothing else
    can appear in a validated 5-field expression.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_schedule_table(svc: "CompiledService") -> str:
    """One clock's payload: a flat YAML map of job name -> cron expression.

    This is what reaches the container, verbatim, as the value of
    ``DOCEX_SCHEDULES_YAML``. Job names are emitted in sorted order so the
    output is deterministic. Returns just the header when the service
    declares no schedules (which validation forbids on a clock).
    """
    schedules = svc.schedules or {}
    lines = [_HEADER]
    for job in sorted(schedules):
        lines.append(f"{job}: {_yaml_quote(schedules[job])}\n")
    return "".join(lines)


def render_schedules_file(compiled: "CompiledEnv") -> str:
    """The visibility artifact written to ``infra/output/<env>/schedules.yml``:
    a map of ``<codebase>.<service>`` -> that clock's flat job map, clocks in
    sorted order.

    **File shape != payload shape, deliberately.** The artifact is keyed by
    dotted clock ref; the payload delivered to a clock is its bare job map.
    Byte-identity between the two is only purchasable by injecting the clock's
    own identity as an env var so it can find its own section — which charges
    the cost in the one place that matters most, the entrypoint every
    downstream project copies, in exchange for a property only the compiler
    cares about. An application must not need to know its own name to find its
    own schedules. The doctrine caps clocks at one per codebase-with-schedules
    (``clock.md`` § One clock per codebase with scheduled work), so the
    artifact is a single-entry file in nearly every real project.

    ``schedules.yml`` is the **visibility** artifact and
    ``DOCEX_SCHEDULES_YAML`` is the **delivery** mechanism. Nothing reads this
    file at runtime, and that is not an oversight: it is what makes schedules
    git-tracked and diff-visible per ``cicl.md`` § Compiler Output, which is
    one of the reasons schedules live in ``infra.yml`` at all. Do not delete
    it for being unmounted.
    """
    out = [
        _HEADER,
        f"# project: {compiled.project} v{compiled.project_version}\n",
        f"# env: {compiled.env} (foundation: {compiled.foundation})\n",
    ]
    for name in sorted(compiled.services):
        svc = compiled.services[name]
        if not svc.schedules:
            continue
        out.append(f"{svc.codebase}.{svc.service}:\n")
        for job in sorted(svc.schedules):
            out.append(f"  {job}: {_yaml_quote(svc.schedules[job])}\n")
    return "".join(out)


def has_clock(compiled: "CompiledEnv") -> bool:
    """Whether ``compiled`` contains at least one service with schedules."""
    return any(s.schedules for s in compiled.services.values())


def schedule_env(svc: "CompiledService") -> dict[str, str] | None:
    """The env vars carrying this clock's schedule table, or None if not a clock.

    One variable, identical on both foundations, whose value is the LITERAL
    rendered YAML rather than a path to it (clock.md § How the schedule reaches
    the container). Returned UNESCAPED — escaping belongs to each emitter's own
    reader (compose interpolation on fixed, ``_hcl_value`` on elastic).

    The delivered value is the clock's **own flat job map**, never the
    aggregate written to ``schedules.yml``.

    WHY a bare dict rather than a ``ScheduleDelivery`` record with
    ``config_key`` / ``mount_target`` / ``foundation`` fields: the operator's
    Q1 ruling is a single mechanism, and permanently-``None`` fields would be a
    standing invitation to reintroduce the per-foundation split.
    """
    if not svc.schedules:
        return None
    return {SCHEDULES_ENV_KEY: render_schedule_table(svc)}
