"""Emit ``infra/secrets/example.env``.

For each backing service, the example.env documents every env var
the service's engine declares in its transfer-table ``env:`` block,
grouped by service with comment headers.
"""

from __future__ import annotations

from pathlib import Path

from docex.cicl.model import CICLDocument
from docex.cicl.transfer import TransferTables


def emit_example_env(
    doc: CICLDocument, tables: TransferTables, out_path: Path
) -> None:
    lines: list[str] = [
        "# Generated by `docex compile`. Do not edit by hand.",
        "# Documents every runtime env var the project's services require.",
        "# Copy this to <env>.env in this directory and fill in real values.",
        "",
    ]
    any_emitted = False
    for name in sorted(doc.backing_services):
        svc = doc.backing_services[name]
        engine_decls = svc.engine if isinstance(svc.engine, list) else [svc.engine]
        env_for_service: dict[str, str] = {}
        # Union over all candidate engines (some are fixed-only, some elastic).
        for cand in engine_decls:
            try:
                entry = tables.engine(svc.role, cand)
            except Exception:
                continue
            for k, v in (entry.env or {}).items():
                env_for_service.setdefault(k, v)
        if not env_for_service:
            continue
        any_emitted = True
        lines.append(f"# {name} ({', '.join(engine_decls)})")
        for k in sorted(env_for_service):
            desc = env_for_service[k]
            lines.append(f"# {desc}")
            lines.append(f"{k}=")
        lines.append("")
    if not any_emitted:
        lines.append("# (no backing services declare runtime env vars)")
    out_path.write_text("\n".join(lines))
