"""Emit ``infra/secrets/example.env``.

The example.env is a committed, keys-only manifest of the operator-
supplied secrets the project requires, grouped by service with comment
headers (cicl.md § example.env, config_and_secrets.md § 2.1):

- each core service's ``secrets:`` block (bespoke, operator-supplied
  secrets like API keys / tokens), and
- each backing engine's ``env:`` vars whose ``kind`` is ``secret``.

Engine env vars of kind ``fixed`` (inlined at compile) and ``minted``
(generated by docex into the TTE store) are deliberately excluded — they
are never operator-supplied, so they have no place in a secrets manifest.
"""

from __future__ import annotations

from pathlib import Path

from docex.cicl.model import CICLDocument
from docex.cicl.transfer import TransferTables


def emit_example_env(
    doc: CICLDocument, tables: TransferTables, out_path: Path
) -> None:
    lines: list[str] = [
        "# Generated by `docex compile`. Do not edit by hand.",
        "# Keys-only manifest of the operator-supplied secrets this project",
        "# requires. Reconcile it into <env>.env with",
        "# `docex secrets scaffold <env>`; never fill values in here.",
        "",
    ]
    any_emitted = False
    # Doctrine-injected secrets surface first — they're required on every
    # project regardless of which services it declares. Mod 017.
    lines.extend([
        "# Doctrine-injected secrets",
        "# The OTel collector sidecar's authentication key against",
        "# observability_backend_url. Required in stage/prod; sidecars in",
        "# dev/test use the `debug` exporter (stdout) and ignore this key.",
        "TELEMETRY_API_KEY=",
        "",
    ])
    any_emitted = True
    # Core-service bespoke secrets first (the app's own keys/tokens).
    for name in sorted(doc.core_services):
        secrets = doc.core_services[name].secrets or {}
        if not secrets:
            continue
        any_emitted = True
        lines.append(f"# {name} (core service)")
        for k in sorted(secrets):
            lines.append(f"# {secrets[k]}")
            lines.append(f"{k}=")
        lines.append("")
    for name in sorted(doc.backing_services):
        svc = doc.backing_services[name]
        engine_decls = svc.engine if isinstance(svc.engine, list) else [svc.engine]
        env_for_service: dict[str, str] = {}
        # Union over all candidate engines (some are fixed-only, some elastic).
        for cand in engine_decls:
            try:
                entry = tables.engine(svc.role, cand)
            except Exception:
                continue
            for k, spec in (entry.env or {}).items():
                # Only operator-supplied secrets belong in the manifest;
                # fixed vars are inlined and minted vars go to the TTE store.
                if spec.kind != "secret":
                    continue
                env_for_service.setdefault(k, spec.desc)
        if not env_for_service:
            continue
        any_emitted = True
        lines.append(f"# {name} ({', '.join(engine_decls)})")
        for k in sorted(env_for_service):
            desc = env_for_service[k]
            lines.append(f"# {desc}")
            lines.append(f"{k}=")
        lines.append("")
    if not any_emitted:
        lines.append("# (no backing services declare runtime env vars)")
    out_path.write_text("\n".join(lines))
