"""Emit ``infra/secrets/example.env``.

The example.env documents every runtime secret the project's services
require, grouped by service with comment headers:

- each backing service's engine ``env:`` block (e.g. POSTGRES_USER), and
- each core service's ``secrets:`` block (bespoke, operator-supplied
  secrets like API keys / tokens).
"""

from __future__ import annotations

from pathlib import Path

from docex.cicl.model import CICLDocument
from docex.cicl.transfer import TransferTables


def emit_example_env(
    doc: CICLDocument, tables: TransferTables, out_path: Path
) -> None:
    lines: list[str] = [
        "# Generated by `docex compile`. Do not edit by hand.",
        "# Documents every runtime env var the project's services require.",
        "# Copy this to <env>.env in this directory and fill in real values.",
        "",
    ]
    any_emitted = False
    # Core-service bespoke secrets first (the app's own keys/tokens).
    for name in sorted(doc.core_services):
        secrets = doc.core_services[name].secrets or {}
        if not secrets:
            continue
        any_emitted = True
        lines.append(f"# {name} (core service)")
        for k in sorted(secrets):
            lines.append(f"# {secrets[k]}")
            lines.append(f"{k}=")
        lines.append("")
    for name in sorted(doc.backing_services):
        svc = doc.backing_services[name]
        engine_decls = svc.engine if isinstance(svc.engine, list) else [svc.engine]
        env_for_service: dict[str, str] = {}
        # Union over all candidate engines (some are fixed-only, some elastic).
        for cand in engine_decls:
            try:
                entry = tables.engine(svc.role, cand)
            except Exception:
                continue
            for k, v in (entry.env or {}).items():
                env_for_service.setdefault(k, v)
        if not env_for_service:
            continue
        any_emitted = True
        lines.append(f"# {name} ({', '.join(engine_decls)})")
        for k in sorted(env_for_service):
            desc = env_for_service[k]
            lines.append(f"# {desc}")
            lines.append(f"{k}=")
        lines.append("")
    if not any_emitted:
        lines.append("# (no backing services declare runtime env vars)")
    out_path.write_text("\n".join(lines))
