"""Aggregation — merge the three configurable-value categories into the
container-facing env just before bring-up. Foundation-dispatched like
run_migrate. Mod 080 implements dev/test; Mod 081 the fixed stage/prod
release; elastic stage/prod lands in Mod 082.
See config_and_secrets.md § Aggregation."""
from __future__ import annotations

from typing import TYPE_CHECKING
from pathlib import Path

from docex.cicl.categories import minted_policies
from docex.cicl.generate import generate
from docex.context import ProjectContext
from docex.envfile import parse_env_text, read_env_file, write_env_file
from docex.errors import AggregationError, SSMPushFailed

if TYPE_CHECKING:
    from docex.aws.client import AWSClient
    from docex.ssh.client import SSHClient

_DEV_TEST = ("dev", "test")
_STAGE_PROD = ("stage", "prod")

# Host layout on a fixed stage/prod machine — the deploy dir the playbook
# renders into. The persistent TTE store and the runtime aggregate both
# live here; docex reads the store back over SSH (host-authoritative).
_HOST_DEPLOY_ROOT = "/opt/{project}/{env}"


def _tte_store_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "tte" / f"{env}.env"


def _secrets_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "secrets" / f"{env}.env"


def _config_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "config" / f"{env}.env"


def aggregate_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / ".docex" / "agg" / f"{env}.env"


def _staged_tte_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / ".docex" / "agg" / f"{env}.tte.env"


def _host_for(ctx: ProjectContext, env: str) -> str:
    from docex.naming import dns_label

    apex = ctx.infra.apex_domain
    return f"{env}.{dns_label(ctx.project.name)}.{apex}"


def _disjoint_union(*sources: tuple[str, dict[str, str]]) -> dict[str, str]:
    """Merge ordered (name, map) sources, refusing any cross-source key
    collision. Compile guarantees disjointness (rule 20); this is defensive."""
    merged: dict[str, str] = {}
    for _name, src in sources:
        for k, v in src.items():
            if k in merged:
                raise AggregationError(
                    f"aggregation key collision on {k!r} — should have been "
                    f"caught at compile; check infra.yml categories."
                )
            merged[k] = v
    return merged


def ensure_tte(ctx: ProjectContext, *, env: str) -> dict[str, str]:
    """dev/test: generate-if-absent minted values into infra/tte/<env>.env
    (the authoritative store compose reads). Preserves existing values; returns
    the current minted key->value map."""
    store = _tte_store_path(ctx, env)
    existing = read_env_file(store)
    policies = minted_policies(ctx.infra, ctx.transfer_tables)
    updated = dict(existing)
    for key, policy in policies.items():
        if key not in updated:
            updated[key] = generate(policy)  # impure — never at compile
    if updated != existing:
        write_env_file(
            store,
            updated,
            header=[
                "docex TTE store — generated engine credentials.",
                "Authoritative for dev/test; gitignored; do not hand-edit.",
            ],
        )
    # Only currently-declared minted keys go to the aggregate.
    return {k: updated[k] for k in policies}


def aggregate(ctx: ProjectContext, *, env: str) -> Path:
    """Build .docex/agg/<env>.env = TTE ∪ secrets ∪ config; return its path.
    dev/test only in Mod 080."""
    if env not in _DEV_TEST:
        raise AggregationError(
            f"aggregate({env!r}) — stage/prod aggregation lands in Mods 081/082; "
            f"dev/test only for now."
        )
    tte = ensure_tte(ctx, env=env)
    secrets = read_env_file(_secrets_path(ctx, env))
    config = read_env_file(_config_path(ctx, env))
    merged = _disjoint_union(("tte", tte), ("secrets", secrets), ("config", config))
    out = aggregate_path(ctx, env)
    write_env_file(
        out,
        merged,
        header=[
            "Generated by docex aggregation — derived, ephemeral.",
            "TTE ∪ secrets ∪ config. Do not edit; regenerated every bring-up.",
        ],
    )
    return out


def ensure_tte_fixed(
    ctx: ProjectContext, *, env: str, ssh: "SSHClient", key: Path
) -> dict[str, str]:
    """fixed stage/prod: the HOST tte.env is authoritative. SSH-capture it,
    mint only the *missing* minted keys (preserving every host value), and
    stage the resulting superset to .docex/agg/<env>.tte.env for ansible to
    render back onto the host. Returns the current minted key->value map.

    WHY host-authoritative: re-minting a key the host already has would lock
    the host's running containers out of their own credentials on the next
    release (config_and_secrets.md § authoritative-store rule)."""
    host = _host_for(ctx, env)
    remote = _HOST_DEPLOY_ROOT.format(project=ctx.project.name, env=env) + "/tte.env"
    # WHY sudo: the playbook renders tte.env root:root 0600 (become=root), so
    # the `deploy` SSH user must sudo to read it. A plain `cat` returns
    # "Permission denied" — which `2>/dev/null` would mask into an empty read,
    # making docex re-mint every release and clobber the live DB credential (the
    # exact lockout the authoritative-store rule prevents). `deploy` has
    # passwordless sudo (release_mechanism.md § Fixed Foundation: Ansible).
    # ``|| true`` so a not-yet-provisioned store (first release) reads as
    # empty rather than a non-zero cat; a real connection failure is 255.
    rc, out = ssh.capture(host, key, f"sudo cat {remote} 2>/dev/null || true")
    if rc == 255:
        raise AggregationError(
            f"cannot reach host {host!r} to read the TTE store (ssh 255)"
        )
    existing = parse_env_text(out, source=f"{host}:{remote}")
    policies = minted_policies(ctx.infra, ctx.transfer_tables)
    updated = dict(existing)
    for k, policy in policies.items():
        if k not in updated:
            updated[k] = generate(policy)  # impure — never at compile
    write_env_file(
        _staged_tte_path(ctx, env),
        updated,
        header=[
            "docex TTE store (host-authoritative superset).",
            "Rendered to /opt/<project>/<env>/tte.env by the playbook.",
        ],
    )
    # Only currently-declared minted keys go to the aggregate.
    return {k: updated[k] for k in policies}


def aggregate_fixed_prod(
    ctx: ProjectContext, *, env: str, ssh: "SSHClient", key: Path
) -> tuple[Path, Path]:
    """fixed stage/prod: build the runtime aggregate AND stage the host TTE
    superset. Returns (aggregate_path, staged_tte_path); the caller hands both
    to ansible to render onto the host (`.env` and `tte.env` respectively)."""
    if env not in _STAGE_PROD:
        raise AggregationError(
            f"aggregate_fixed_prod({env!r}) — fixed release aggregation is "
            f"stage/prod only; dev/test use aggregate()."
        )
    tte = ensure_tte_fixed(ctx, env=env, ssh=ssh, key=key)
    secrets = read_env_file(_secrets_path(ctx, env))
    config = read_env_file(_config_path(ctx, env))
    merged = _disjoint_union(("tte", tte), ("secrets", secrets), ("config", config))
    out = aggregate_path(ctx, env)
    write_env_file(
        out,
        merged,
        header=[
            "Generated by docex aggregation — derived, ephemeral.",
            "TTE ∪ secrets ∪ config. Do not edit; regenerated every release.",
        ],
    )
    return out, _staged_tte_path(ctx, env)


def _ssm_path(project: str, env: str, key: str) -> str:
    return f"/{project}/{env}/{key}"


def _ssm_put(
    aws: "AWSClient", path: str, value: str, *, overwrite: bool, param_type: str
) -> None:
    """Push one parameter, translating any boto-level failure into
    ``SSMPushFailed`` so a release aborts before touching tofu (mirrors the
    fail-fast semantics of the superseded ``_push_secrets``)."""
    try:
        aws.ssm_put_parameter(
            path, value, overwrite=overwrite, param_type=param_type
        )
    except SSMPushFailed:
        raise
    except Exception as e:
        raise SSMPushFailed(f"failed pushing {path!r} to SSM: {e}") from e


def ensure_tte_elastic(ctx: ProjectContext, *, env: str, aws: "AWSClient") -> int:
    """elastic stage/prod: mint-if-absent each minted key into SSM as a
    ``SecureString`` (put-if-absent). SSM is the authoritative store on
    elastic — a present value is left untouched (write-once). Returns the
    count newly minted.

    WHY read-before-mint: re-minting a key SSM already holds would lock the
    live ECS tasks (and RDS) out of their own credentials. A lost local copy
    can never clobber the live value because docex only mints when SSM is
    empty (config_and_secrets.md § authoritative-store rule)."""
    project = ctx.project.name
    policies = minted_policies(ctx.infra, ctx.transfer_tables)
    minted = 0
    for key, policy in policies.items():
        path = _ssm_path(project, env, key)
        if aws.ssm_get_parameter(path) is None:
            _ssm_put(
                aws,
                path,
                generate(policy),  # impure — never at compile
                overwrite=False,
                param_type="SecureString",
            )
            minted += 1
    return minted


def aggregate_elastic(ctx: ProjectContext, *, env: str, aws: "AWSClient") -> int:
    """elastic stage/prod: push all three categories to the SSM prefix
    ``/<project>/<env>/`` — the elastic aggregate is the prefix itself (there
    is no aggregate file). TTE put-if-absent (SecureString), secrets overwrite
    (SecureString), config overwrite (String). Returns total params written
    (minted + pushed). See config_and_secrets.md § 4.2."""
    if env not in _STAGE_PROD:
        raise AggregationError(
            f"aggregate_elastic({env!r}) — elastic release aggregation is "
            f"stage/prod only; dev/test use aggregate()."
        )
    project = ctx.project.name
    tte_keys = set(minted_policies(ctx.infra, ctx.transfer_tables))
    secrets = read_env_file(_secrets_path(ctx, env))
    config = read_env_file(_config_path(ctx, env))
    # Defensive disjointness — compile guarantees the *declared* categories
    # are disjoint (rule 20); the operator-maintained files are re-checked
    # here, mirroring the fixed path's _disjoint_union guard.
    overlaps = (
        (tte_keys & set(secrets))
        | (tte_keys & set(config))
        | (set(secrets) & set(config))
    )
    if overlaps:
        raise AggregationError(
            f"SSM aggregation key collision for env {env!r}: {sorted(overlaps)} "
            f"appear in more than one category — should have been caught at "
            f"compile; check infra.yml / the secrets & config files."
        )
    n = ensure_tte_elastic(ctx, env=env, aws=aws)
    for key, value in secrets.items():
        _ssm_put(
            aws, _ssm_path(project, env, key), value,
            overwrite=True, param_type="SecureString",
        )
        n += 1
    for key, value in config.items():
        _ssm_put(
            aws, _ssm_path(project, env, key), value,
            overwrite=True, param_type="String",
        )
        n += 1
    return n
