"""Aggregation — merge the three configurable-value categories into the
container-facing env just before bring-up. Foundation-dispatched like
run_migrate. Mod 080 implements dev/test; stage/prod land in Mods 081/082.
See config_and_secrets.md § Aggregation."""
from __future__ import annotations

from pathlib import Path

from docex.cicl.categories import minted_policies
from docex.cicl.generate import generate
from docex.context import ProjectContext
from docex.envfile import read_env_file, write_env_file
from docex.errors import AggregationError

_DEV_TEST = ("dev", "test")


def _tte_store_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "tte" / f"{env}.env"


def _secrets_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "secrets" / f"{env}.env"


def _config_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / "infra" / "config" / f"{env}.env"


def aggregate_path(ctx: ProjectContext, env: str) -> Path:
    return ctx.project_root / ".docex" / "agg" / f"{env}.env"


def ensure_tte(ctx: ProjectContext, *, env: str) -> dict[str, str]:
    """dev/test: generate-if-absent minted values into infra/tte/<env>.env
    (the authoritative store compose reads). Preserves existing values; returns
    the current minted key->value map."""
    store = _tte_store_path(ctx, env)
    existing = read_env_file(store)
    policies = minted_policies(ctx.infra, ctx.transfer_tables)
    updated = dict(existing)
    for key, policy in policies.items():
        if key not in updated:
            updated[key] = generate(policy)  # impure — never at compile
    if updated != existing:
        write_env_file(
            store,
            updated,
            header=[
                "docex TTE store — generated engine credentials.",
                "Authoritative for dev/test; gitignored; do not hand-edit.",
            ],
        )
    # Only currently-declared minted keys go to the aggregate.
    return {k: updated[k] for k in policies}


def aggregate(ctx: ProjectContext, *, env: str) -> Path:
    """Build .docex/agg/<env>.env = TTE ∪ secrets ∪ config; return its path.
    dev/test only in Mod 080."""
    if env not in _DEV_TEST:
        raise AggregationError(
            f"aggregate({env!r}) — stage/prod aggregation lands in Mods 081/082; "
            f"dev/test only for now."
        )
    tte = ensure_tte(ctx, env=env)
    secrets = read_env_file(_secrets_path(ctx, env))
    config = read_env_file(_config_path(ctx, env))
    merged: dict[str, str] = {}
    for _source_name, src in (("tte", tte), ("secrets", secrets), ("config", config)):
        for k, v in src.items():
            if k in merged:
                # Compile guarantees disjointness (rule 20); defensive only.
                raise AggregationError(
                    f"aggregation key collision on {k!r} (env {env}) — should "
                    f"have been caught at compile; check infra.yml categories."
                )
            merged[k] = v
    out = aggregate_path(ctx, env)
    write_env_file(
        out,
        merged,
        header=[
            "Generated by docex aggregation — derived, ephemeral.",
            "TTE ∪ secrets ∪ config. Do not edit; regenerated every bring-up.",
        ],
    )
    return out
