"""``docex docs adr`` — regenerate the two ADR index files from ADR sources.

Reads every ``*.md`` under ``plans/design/adrs/``, parses each file's YAML
frontmatter, and regenerates ``plans/design/adr_index.md`` (all ADRs) and
``plans/design/adr_active.md`` (accepted + not-superseded). Deterministic
(stable id sort) and idempotent (byte-identical on re-run).

The render functions here are the SINGLE canonical definition of both files'
exact bytes. ``docs scaffold`` uses them for its empty-set stubs and
``docs check`` uses them for the staleness gate, so the three can never
disagree on the generated content.

See doctrine/practices/adrs.md § ADR Format and § ADR Index.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from docex.context import ProjectContext

# First line of each generated file — the "do not hand-edit" marker.
GENERATED_MARKER = "<!-- generated by `docex docs adr` — do not edit by hand -->"

_ADRS_SUBDIR = "design/adrs"
_INDEX_REL = "design/adr_index.md"
_ACTIVE_REL = "design/adr_active.md"


@dataclass(frozen=True)
class Adr:
    id: str
    title: str
    status: str
    date: str
    supersedes: tuple[str, ...]
    superseded_by: tuple[str, ...]
    tags: tuple[str, ...]
    # The ADR's real on-disk filename (e.g. "0001_foo.md"), captured by
    # parse_adr. The index links to THIS, never a path derived from id+title,
    # which could drift from the actual file and dangle. See mod 170.
    filename: str

    @property
    def is_active(self) -> bool:
        # "accepted AND not superseded" — status already excludes
        # proposed/rejected/superseded/deprecated; the empty-superseded_by
        # guard also drops an inconsistent "accepted" ADR that a later ADR
        # has in fact superseded.
        return self.status == "accepted" and not self.superseded_by


def _frontmatter_block(text: str) -> str | None:
    """Return the raw YAML between the leading ``---`` fences, or None."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[1:i])
    return None  # unterminated frontmatter


def _parse_frontmatter(text: str) -> dict:
    block = _frontmatter_block(text)
    if block is None:
        return {}
    # BaseLoader keeps ALL scalars as strings: no implicit int/date/bool
    # coercion. This is load-bearing — pyyaml's default loader would parse a
    # zero-padded id like `0004` as octal int 4 (dropping the padding) while
    # leaving `0009` a string, an inconsistency that would corrupt ids.
    data = yaml.load(block, Loader=yaml.BaseLoader)  # noqa: S506 (BaseLoader is safe)
    return data if isinstance(data, dict) else {}


def _as_id_list(value) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, (list, tuple)):
        return tuple(str(v).strip() for v in value if str(v).strip())
    s = str(value).strip()
    return (s,) if s else ()


def parse_adr(path: Path) -> Adr:
    data = _parse_frontmatter(path.read_text(encoding="utf-8"))
    return Adr(
        id=str(data.get("id", "")).strip(),
        title=str(data.get("title", "")).strip(),
        status=str(data.get("status", "")).strip(),
        date=str(data.get("date", "")).strip(),
        supersedes=_as_id_list(data.get("supersedes")),
        superseded_by=_as_id_list(data.get("superseded-by")),
        tags=_as_id_list(data.get("tags")),
        filename=path.name,
    )


def load_adrs(project_root: Path) -> list[Adr]:
    """Parse every ``*.md`` directly under ``plans/design/adrs/``."""
    adrs_dir = project_root / "plans" / _ADRS_SUBDIR
    if not adrs_dir.is_dir():
        return []
    return [parse_adr(p) for p in sorted(adrs_dir.glob("*.md"))]


def _sort_key(a: Adr):
    # Numeric ids sort numerically; any non-numeric id sorts after, by string.
    return (0, int(a.id)) if a.id.isdigit() else (1, a.id)


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _adr_link(a: Adr) -> str:
    """Render the ADR id as a markdown link to its source file.

    The path is relative to the index files, which both sit at plans/design/, so
    it targets plans/design/adrs/<file>. The link TEXT is the ADR id; the link
    TARGET is the ADR's real on-disk filename (``Adr.filename``) — never a path
    derived from id+title, which could drift from the actual file and dangle. This
    resolvable link is what makes an ADR reachable from the index root in
    ``docs check`` (doctrine/practices/docs.md § Reachability Check).
    """
    return f"[{a.id}](adrs/{a.filename})"


def render_index(adrs: list[Adr]) -> str:
    """Render adr_index.md (ALL ADRs). Canonical bytes; ends with newline."""
    lines = [
        GENERATED_MARKER,
        "",
        "# ADR Index",
        "",
        "| ADR ID | Title | Status | Date | Supersedes | Superseded By |",
        "| ------ | ----- | ------ | ---- | ---------- | ------------- |",
    ]
    for a in sorted(adrs, key=_sort_key):
        lines.append(_row([
            _adr_link(a), a.title, a.status, a.date,
            ", ".join(a.supersedes), ", ".join(a.superseded_by),
        ]))
    return "\n".join(lines) + "\n"


def render_active(adrs: list[Adr]) -> str:
    """Render adr_active.md (accepted + not superseded). Ends with newline."""
    lines = [
        GENERATED_MARKER,
        "",
        "# Active ADRs",
        "",
        "| ADR ID | Title | Date | Supersedes |",
        "| ------ | ----- | ---- | ---------- |",
    ]
    for a in sorted((a for a in adrs if a.is_active), key=_sort_key):
        lines.append(_row([_adr_link(a), a.title, a.date, ", ".join(a.supersedes)]))
    return "\n".join(lines) + "\n"


def _rendered_pairs(project_root: Path) -> tuple[tuple[str, str], ...]:
    adrs = load_adrs(project_root)
    return (
        (_INDEX_REL, render_index(adrs)),
        (_ACTIVE_REL, render_active(adrs)),
    )


def regenerate_adr_indexes(project_root: Path) -> list[str]:
    """Write both index files from ADR sources. Returns the rel-paths whose
    content actually changed (idempotent: a no-op run returns [])."""
    plans = project_root / "plans"
    written: list[str] = []
    for rel, content in _rendered_pairs(project_root):
        target = plans / rel
        old = target.read_text(encoding="utf-8") if target.is_file() else None
        if old != content:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(f"plans/{rel}")
    return written


def adr_index_drift(project_root: Path) -> list[str]:
    """Index files whose on-disk content differs from the canonical render.

    A MISSING index file is not reported here — ``missing_standard_files``
    owns that — so the two checks never double-report the same file.
    """
    plans = project_root / "plans"
    problems: list[str] = []
    for rel, content in _rendered_pairs(project_root):
        target = plans / rel
        if not target.is_file():
            continue
        if target.read_text(encoding="utf-8") != content:
            problems.append(
                f"stale ADR index: plans/{rel} out of sync with "
                f"plans/{_ADRS_SUBDIR}/ — run `docex docs adr`"
            )
    return problems


def run_docs_adr(ctx: ProjectContext) -> int:
    written = regenerate_adr_indexes(ctx.project_root)
    if written:
        print(f"docex docs adr: regenerated {len(written)} file(s):")
        for rel in written:
            print(f"  ~ {rel}")
    else:
        print("docex docs adr: ADR indexes already up to date.")
    return 0
