# Generated by `docex compile`. Do not edit by hand.
# project: docex_smoke_elastic v0.0.8
# tier: project (foundation: elastic)
# domain: doctrine-elastic.luxrnd.tech
#
# The resources here back every elastic environment's main.tf via
# `data "terraform_remote_state" "project"`. They are applied by
# `docex bootstrap` against their own state file (project/terraform.tfstate)
# in the same S3 backend the bootstrap creates.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {
    bucket         = "docex-smoke-elastic-tofu-state"
    key            = "project/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "docex_smoke_elastic_tofu_locks"
    encrypt        = true
  }
}

provider "aws" {
  region = "us-east-1"
}

data "aws_availability_zones" "available" {
  state = "available"
}

# ---------------------------------------------------------------------------
# Route53 hosted zone for the project domain.
#
# The operator must NS-delegate from the parent (registrar or parent hosted
# zone) using the name servers printed by `docex bootstrap` after the first
# apply. Until that delegation propagates, ACM DNS validation will not
# complete, which is why `docex bootstrap` applies this zone first and pauses
# for delegation before proceeding to the cert.
# ---------------------------------------------------------------------------
resource "aws_route53_zone" "project" {
  name = "doctrine-elastic.luxrnd.tech"
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# VPC + IGW + public/private subnets across two AZs + NAT gateways.
# ---------------------------------------------------------------------------
resource "aws_vpc" "project" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
    Name       = "docex_smoke_elastic"
  }
}

resource "aws_internet_gateway" "project" {
  vpc_id = aws_vpc.project.id
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
}

resource "aws_subnet" "public" {
  count                   = 2
  vpc_id                  = aws_vpc.project.id
  cidr_block              = cidrsubnet(aws_vpc.project.cidr_block, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true
  tags = {
    project    = "docex_smoke_elastic"
    tier       = "public"
    managed_by = "doctrine"
    Name       = "docex_smoke_elastic_public_${data.aws_availability_zones.available.names[count.index]}"
  }
}

resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.project.id
  cidr_block        = cidrsubnet(aws_vpc.project.cidr_block, 8, 10 + count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = {
    project    = "docex_smoke_elastic"
    tier       = "private"
    managed_by = "doctrine"
    Name       = "docex_smoke_elastic_private_${data.aws_availability_zones.available.names[count.index]}"
  }
}

resource "aws_eip" "nat" {
  count  = 2
  domain = "vpc"
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
}

resource "aws_nat_gateway" "project" {
  count         = 2
  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
  depends_on = [aws_internet_gateway.project]
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.project.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.project.id
  }
  tags = {
    project    = "docex_smoke_elastic"
    tier       = "public"
    managed_by = "doctrine"
  }
}

resource "aws_route_table_association" "public" {
  count          = 2
  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table" "private" {
  count  = 2
  vpc_id = aws_vpc.project.id
  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.project[count.index].id
  }
  tags = {
    project    = "docex_smoke_elastic"
    tier       = "private"
    managed_by = "doctrine"
  }
}

resource "aws_route_table_association" "private" {
  count          = 2
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private[count.index].id
}

# ---------------------------------------------------------------------------
# ACM certificate.
#
# `*.doctrine-elastic.luxrnd.tech` covers the env subdomains (`dev.doctrine-elastic.luxrnd.tech`,
# `test.doctrine-elastic.luxrnd.tech`, `stage.doctrine-elastic.luxrnd.tech`, `www.doctrine-elastic.luxrnd.tech`). The four
# per-env wildcard SANs cover per-service hosts
# (e.g. `backend.stage.doctrine-elastic.luxrnd.tech`).
# ---------------------------------------------------------------------------
resource "aws_acm_certificate" "project" {
  domain_name = "*.doctrine-elastic.luxrnd.tech"
  subject_alternative_names = [
    "*.dev.doctrine-elastic.luxrnd.tech",
    "*.test.doctrine-elastic.luxrnd.tech",
    "*.stage.doctrine-elastic.luxrnd.tech",
    "*.www.doctrine-elastic.luxrnd.tech",
  ]
  validation_method = "DNS"
  lifecycle {
    create_before_destroy = true
  }
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
}

resource "aws_route53_record" "cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.project.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.project.zone_id
}

resource "aws_acm_certificate_validation" "project" {
  certificate_arn         = aws_acm_certificate.project.arn
  validation_record_fqdns = [for record in aws_route53_record.cert_validation : record.fqdn]
}

# ---------------------------------------------------------------------------
# ECR repositories — one per core service. The image refs in each env's
# main.tf resolve to `<repo_url>:<version>`.
# ---------------------------------------------------------------------------

resource "aws_ecr_repository" "web" {
  name                 = "docex_smoke_elastic/web"
  image_tag_mutability = "MUTABLE"
  tags = {
    project    = "docex_smoke_elastic"
    service    = "web"
    managed_by = "doctrine"
  }
}

resource "aws_ecr_repository" "worker" {
  name                 = "docex_smoke_elastic/worker"
  image_tag_mutability = "MUTABLE"
  tags = {
    project    = "docex_smoke_elastic"
    service    = "worker"
    managed_by = "doctrine"
  }
}


# ---------------------------------------------------------------------------
# ECS task execution role.
#
# Fargate assumes this role *during launch* to pull images from ECR,
# fetch SSM parameters referenced in container `secrets[]` blocks, and
# write to CloudWatch Logs. Distinct from any "task role" the app
# itself might use to call AWS APIs at runtime — task role is per-app
# and out of scope for the doctrine skeleton.
#
# Provisioned at the project tier (not per-env) because the role's
# permissions are derived from project identity (the SSM prefix), not
# env identity. Each env's ECS task definitions reference the role ARN
# via terraform_remote_state.
# ---------------------------------------------------------------------------
data "aws_caller_identity" "current" {}

resource "aws_iam_role" "task_execution" {
  name = "docex_smoke_elastic_task_execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    project    = "docex_smoke_elastic"
    managed_by = "doctrine"
  }
}

# AWS-managed policy: covers ECR pulls + CloudWatch Logs writes.
resource "aws_iam_role_policy_attachment" "task_execution_managed" {
  role       = aws_iam_role.task_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# Inline policy: lets Fargate decrypt SecureString parameters from this
# project's SSM prefix, so containers' `secrets[]` entries resolve.
# Scoped to `/${project}/*` so a leaked role can't read other projects.
resource "aws_iam_role_policy" "task_execution_ssm" {
  name = "docex_smoke_elastic_task_execution_ssm"
  role = aws_iam_role.task_execution.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["ssm:GetParameters", "ssm:GetParameter", "ssm:GetParametersByPath"]
        Resource = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/*"
      },
      {
        Effect   = "Allow"
        Action   = ["kms:Decrypt"]
        Resource = "*"
      },
    ]
  })
}

# ---------------------------------------------------------------------------
# Outputs. Consumed by each env's main.tf via terraform_remote_state.
# ---------------------------------------------------------------------------
output "vpc_id" {
  value = aws_vpc.project.id
}

output "public_subnet_ids" {
  value = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  value = aws_subnet.private[*].id
}

output "zone_id" {
  value = aws_route53_zone.project.zone_id
}

output "zone_name_servers" {
  value = aws_route53_zone.project.name_servers
}

output "certificate_arn" {
  value = aws_acm_certificate_validation.project.certificate_arn
}

output "task_execution_role_arn" {
  value = aws_iam_role.task_execution.arn
}

output "ecr_repository_web_url" {
  value = aws_ecr_repository.web.repository_url
}

output "ecr_repository_worker_url" {
  value = aws_ecr_repository.worker.repository_url
}

