# Generated by `docex compile`. Do not edit by hand.
# project: docex_smoke_elastic v0.0.4
# env: stage (foundation: elastic)
# apex_domain: luxrnd.tech -> stage.docex-smoke-elastic.luxrnd.tech

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  # State backend reference (provisioned by `docex bootstrap`).
  backend "s3" {
    bucket         = "docex-smoke-elastic-tofu-state"
    key            = "stage/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "docex_smoke_elastic_tofu_locks"
    encrypt        = true
  }
}

provider "aws" {
  region = "us-east-1"
}

# AWS account ID — used downstream for SSM parameter ARNs in ECS
# secrets[] blocks. Resolved at apply time so `docex compile` stays
# offline-pure (no AWS creds required for compile).
data "aws_caller_identity" "current" {}

# ---------------------------------------------------------------------------
# Project-tier outputs (VPC, subnets, Route53 zone, ACM cert, ECR repos).
# Provisioned once by `docex bootstrap` against ../project/production/main.tf;
# the env-tier apply just composes them.
# ---------------------------------------------------------------------------
data "terraform_remote_state" "project" {
  backend = "s3"
  config = {
    bucket = "docex-smoke-elastic-tofu-state"
    key    = "project/terraform.tfstate"
    region = "us-east-1"
  }
}

# ---------------------------------------------------------------------------
# Network plane (security groups; one per CICL-declared network)
# ---------------------------------------------------------------------------
resource "aws_security_group" "internal" {
  # WHY: data-plane name per networks.md § Compiled Names — hyphenated form
  # regardless of the project's underscore form.
  name        = "docex-smoke-elastic-stage-internal"
  description = "internal network for docex_smoke_elastic stage"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  # WHY: aws_security_group denies egress when no egress block is given,
  # overriding AWS's allow-all default. Without this, Fargate tasks can't
  # reach SSM/ECR. Per-network egress restriction is deferred — see
  # infrastructure.md § Deferred rule 6.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    project    = "docex_smoke_elastic"
    env        = "stage"
    network    = "internal"
    managed_by = "doctrine"
  }
}

# Internal SG: accepts ingress only from itself (services in the same network).
resource "aws_security_group_rule" "internal_self_ingress" {
  type              = "ingress"
  from_port         = 0
  to_port           = 65535
  protocol          = "tcp"
  security_group_id = aws_security_group.internal.id
  self              = true
}

resource "aws_security_group" "web" {
  # WHY: data-plane name per networks.md § Compiled Names — hyphenated form
  # regardless of the project's underscore form.
  name        = "docex-smoke-elastic-stage-web"
  description = "web network for docex_smoke_elastic stage"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  # WHY: aws_security_group denies egress when no egress block is given,
  # overriding AWS's allow-all default. Without this, Fargate tasks can't
  # reach SSM/ECR. Per-network egress restriction is deferred — see
  # infrastructure.md § Deferred rule 6.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    project    = "docex_smoke_elastic"
    env        = "stage"
    network    = "web"
    managed_by = "doctrine"
  }
}

# Web SG: open ingress only from the project reverse-proxy SG (project-tier).
# Mod 044: source SG is polymorphic — `alb` projects use the project ALB's SG,
# `ec2_traefik_*` projects use the project's traefik EC2 SG. Both expose the
# value via the project-tier `reverse_proxy_security_group_id` output.
resource "aws_security_group_rule" "web_ingress_from_reverse_proxy" {
  type                     = "ingress"
  from_port                = 0
  to_port                  = 65535
  protocol                 = "tcp"
  security_group_id        = aws_security_group.web.id
  source_security_group_id = data.terraform_remote_state.project.outputs.reverse_proxy_security_group_id
}



# ---------------------------------------------------------------------------
# ECS cluster
# ---------------------------------------------------------------------------
resource "aws_ecs_cluster" "cluster" {
  name = "docex-smoke-elastic-stage"
  tags = {
    project    = "docex_smoke_elastic"
    env        = "stage"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# Service discovery — ECS Service Connect over a Cloud Map PRIVATE DNS
# namespace. Per shape2.md § Elastic-Foundation, one namespace per env,
# associated with the master VPC. Auto-creates a Route53 private hosted
# zone resolvable VPC-wide so EC2-traefik (mod 044) and other non-ECS
# consumers can reach services by name. ECS tasks inside the namespace
# resolve by discoveryName alone via the Envoy sidecar; consumers
# outside the namespace use the FQDN form <discoveryName>.<namespace>.
# ---------------------------------------------------------------------------
resource "aws_service_discovery_private_dns_namespace" "env" {
  # Mod 046: Cloud Map private DNS namespaces resolve via Route53; the name
  # must be a valid DNS hostname, so the project segment is DNS-labeled
  # (underscores → hyphens, lowercased) — the joiner is already a hyphen
  # per mod 040, but underscores inside an underscored project name would
  # survive without this filter and AWS would reject the resource.
  name        = "docex-smoke-elastic-stage"
  vpc         = data.terraform_remote_state.project.outputs.vpc_id
  description = "ECS Service Connect namespace for docex-smoke-elastic stage"
  tags = {
    project    = "docex_smoke_elastic"
    env        = "stage"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# Services (backing first, then core; dispatch is by engine.emits.elastic).
# Per Mod 013, both backing and core services flow through the same
# destination-driven renderer — what HCL gets emitted is governed by the
# engine's declared emit destinations.
# ---------------------------------------------------------------------------
data "aws_ssm_parameter" "appdb_postgres_user" {
  name            = "/docex_smoke_elastic/stage/POSTGRES_USER"
  with_decryption = true
}
data "aws_ssm_parameter" "appdb_postgres_password" {
  name            = "/docex_smoke_elastic/stage/POSTGRES_PASSWORD"
  with_decryption = true
}

resource "aws_db_instance" "appdb" {
  allocated_storage = 20
  backup_retention_period = 7
  db_name = "appdb"
  db_subnet_group_name = aws_db_subnet_group.appdb.name
  deletion_protection = true
  engine = "postgres"
  engine_version = "15"
  identifier = "docex-smoke-elastic-stage-appdb"
  instance_class = "db.t3.medium"
  password = data.aws_ssm_parameter.appdb_postgres_password.value
  publicly_accessible = false
  storage_encrypted = false
  storage_type = "gp3"
  tags = {
    env = "stage"
    managed_by = "doctrine"
    project = "docex_smoke_elastic"
    role = "relational_db"
    service = "appdb"
  }
  username = data.aws_ssm_parameter.appdb_postgres_user.value
  vpc_security_group_ids = [aws_security_group.internal.id]
}

resource "aws_db_subnet_group" "appdb" {
  name       = "docex-smoke-elastic-stage-appdb"
  subnet_ids = data.terraform_remote_state.project.outputs.private_subnet_ids
}


resource "aws_ecs_task_definition" "events" {
  family                   = "docex-smoke-elastic-stage-events"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "1024"
  memory                   = "4096"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  volume {
    name = "data"
    efs_volume_configuration {
      file_system_id     = aws_efs_file_system.events.id
      transit_encryption = "ENABLED"
    }
  }
  container_definitions = jsonencode([
    {
      essential = true
      image = "clickhouse/clickhouse-server:24.10"
      mountPoints = [{
          containerPath = "/var/lib/clickhouse"
          readOnly = false
          sourceVolume = "data"
        }]
      name = "events"
      portMappings = [{
          containerPort = 9000
          name = "events"
          protocol = "tcp"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "stage", service = "events", role = "analytics_db", managed_by = "doctrine" }
}

resource "aws_ecs_service" "events" {
  name            = "docex-smoke-elastic-stage-events"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.events.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = [data.terraform_remote_state.project.outputs.primary_private_subnet_id]
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_private_dns_namespace.env.arn
    service {
      port_name      = "events"
      discovery_name = "docex-smoke-elastic-stage-events"
      client_alias {
        port     = 9000
        dns_name = "docex-smoke-elastic-stage-events"
      }
    }
  }
}

resource "aws_efs_file_system" "events" {
  creation_token   = "docex-smoke-elastic-stage-events"
  encrypted        = true
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  tags = { project = "docex_smoke_elastic", env = "stage", service = "events", role = "analytics_db", managed_by = "doctrine" }
}

resource "aws_efs_backup_policy" "events" {
  file_system_id = aws_efs_file_system.events.id
  backup_policy {
    status = "ENABLED"
  }
}

resource "aws_efs_mount_target" "events" {
  count           = length(data.terraform_remote_state.project.outputs.private_subnet_ids)
  file_system_id  = aws_efs_file_system.events.id
  subnet_id       = data.terraform_remote_state.project.outputs.private_subnet_ids[count.index]
  security_groups = [aws_security_group.internal.id]
}


resource "aws_ecs_task_definition" "probe" {
  family                   = "docex-smoke-elastic-stage-probe"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  container_definitions = jsonencode([
    {
      essential = true
      image = "nginx:1.27-alpine"
      name = "probe"
      portMappings = [{
          containerPort = 80
          name = "probe"
          protocol = "tcp"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "stage", service = "probe", role = "sidecar", managed_by = "doctrine" }
}

resource "aws_ecs_service" "probe" {
  name            = "docex-smoke-elastic-stage-probe"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.probe.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = [data.terraform_remote_state.project.outputs.primary_private_subnet_id]
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_private_dns_namespace.env.arn
    service {
      port_name      = "probe"
      discovery_name = "docex-smoke-elastic-stage-probe"
      client_alias {
        port     = 80
        dns_name = "docex-smoke-elastic-stage-probe"
      }
    }
  }
}


resource "aws_ecs_task_definition" "web" {
  family                   = "docex-smoke-elastic-stage-web"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  ephemeral_storage {
    size_in_gib = 24
  }
  container_definitions = jsonencode([
    {
      dependsOn = [{
          condition = "START"
          containerName = "web-otelcol"
        }]
      environment = [{
          name = "CLICKHOUSE_HOST"
          value = "docex-smoke-elastic-stage-events"
        }, {
          name = "CLICKHOUSE_PORT"
          value = "9000"
        }, {
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.4,deployment.environment.name=stage"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "web"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.4"
        }, {
          name = "SIDECAR_HOST"
          value = "docex-smoke-elastic-stage-probe"
        }, {
          name = "SIDECAR_PORT"
          value = "80"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_web_url}:0.0.4"
      name = "web"
      portMappings = [{
          containerPort = 8080
          name = "web"
          protocol = "tcp"
        }]
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_USER"
        }]
    },
    {
      command = ["--config=env:OTEL_CONFIG_YAML"]
      cpu = 102
      environment = [{
          name = "OTEL_CONFIG_YAML"
          value = "# Generated by `docex compile`. Do not edit by hand.\n# env: stage\nreceivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 127.0.0.1:4318\nprocessors:\n  batch: {}\nexporters:\n  otlphttp:\n    endpoint: $${env:OBSERVABILITY_BACKEND_URL}\n    headers:\n      authorization: $${env:TELEMETRY_API_KEY}\nextensions:\n  health_check:\n    endpoint: 127.0.0.1:13133\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces:  { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    metrics: { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    logs:    { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n"
        }, {
          name = "OBSERVABILITY_BACKEND_URL"
          value = "https://hyperdx.luxrnd.tech"
        }]
      essential = false
      image = "otel/opentelemetry-collector:0.153.0@sha256:74edb825a429b415262e7eb7a99ed77685c9b2b7238ef69fb42a3625df75458f"
      memory = 128
      name = "web-otelcol"
      secrets = [{
          name = "TELEMETRY_API_KEY"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/TELEMETRY_API_KEY"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "stage", service = "web", role = "web", managed_by = "doctrine" }
}

resource "aws_ecs_task_definition" "web_migrate" {
  family                   = "docex-smoke-elastic-stage-web-migrate"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  container_definitions = jsonencode([
    {
      command = ["/service/migrate.sh"]
      environment = [{
          name = "CLICKHOUSE_HOST"
          value = "docex-smoke-elastic-stage-events"
        }, {
          name = "CLICKHOUSE_PORT"
          value = "9000"
        }, {
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.4,deployment.environment.name=stage"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "web"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.4"
        }, {
          name = "SIDECAR_HOST"
          value = "docex-smoke-elastic-stage-probe"
        }, {
          name = "SIDECAR_PORT"
          value = "80"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_web_url}:0.0.4"
      name = "web"
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_USER"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "stage", service = "web", role = "migrate", managed_by = "doctrine" }
}

resource "aws_ecs_service" "web" {
  name            = "docex-smoke-elastic-stage-web"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.web.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = [data.terraform_remote_state.project.outputs.primary_private_subnet_id]
    security_groups = [aws_security_group.internal.id, aws_security_group.web.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_private_dns_namespace.env.arn
    service {
      port_name      = "web"
      discovery_name = "docex-smoke-elastic-stage-web"
      client_alias {
        port     = 8080
        dns_name = "docex-smoke-elastic-stage-web"
      }
    }
  }
  load_balancer {
    target_group_arn = aws_lb_target_group.web.arn
    container_name   = "web"
    container_port   = 8080
  }
}

resource "aws_lb_target_group" "web" {
  name        = "docex-smoke-elastic-stage-web-tg"
  port        = 8080
  protocol    = "HTTP"
  target_type = "ip"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  health_check {
    path = "/health"
    healthy_threshold = 2
    unhealthy_threshold = 3
    interval = 30
    timeout = 5
  }
}

resource "aws_lb_listener_rule" "web" {
  listener_arn = data.terraform_remote_state.project.outputs.alb_https_listener_arn
  priority     = 1000
  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.web.arn
  }
  condition {
    host_header {
      values = ["web.stage.docex-smoke-elastic.luxrnd.tech", "stage.docex-smoke-elastic.luxrnd.tech"]
    }
  }
}


resource "aws_ecs_task_definition" "worker" {
  family                   = "docex-smoke-elastic-stage-worker"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  ephemeral_storage {
    size_in_gib = 24
  }
  container_definitions = jsonencode([
    {
      dependsOn = [{
          condition = "START"
          containerName = "worker-otelcol"
        }]
      environment = [{
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.4,deployment.environment.name=stage"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "worker"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.4"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_worker_url}:0.0.4"
      name = "worker"
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/POSTGRES_USER"
        }]
    },
    {
      command = ["--config=env:OTEL_CONFIG_YAML"]
      cpu = 102
      environment = [{
          name = "OTEL_CONFIG_YAML"
          value = "# Generated by `docex compile`. Do not edit by hand.\n# env: stage\nreceivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 127.0.0.1:4318\nprocessors:\n  batch: {}\nexporters:\n  otlphttp:\n    endpoint: $${env:OBSERVABILITY_BACKEND_URL}\n    headers:\n      authorization: $${env:TELEMETRY_API_KEY}\nextensions:\n  health_check:\n    endpoint: 127.0.0.1:13133\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces:  { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    metrics: { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    logs:    { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n"
        }, {
          name = "OBSERVABILITY_BACKEND_URL"
          value = "https://hyperdx.luxrnd.tech"
        }]
      essential = false
      image = "otel/opentelemetry-collector:0.153.0@sha256:74edb825a429b415262e7eb7a99ed77685c9b2b7238ef69fb42a3625df75458f"
      memory = 128
      name = "worker-otelcol"
      secrets = [{
          name = "TELEMETRY_API_KEY"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/TELEMETRY_API_KEY"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "stage", service = "worker", role = "web", managed_by = "doctrine" }
}

resource "aws_ecs_service" "worker" {
  name            = "docex-smoke-elastic-stage-worker"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.worker.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = [data.terraform_remote_state.project.outputs.primary_private_subnet_id]
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_private_dns_namespace.env.arn
  }
}





# ---------------------------------------------------------------------------
# Route53 record: <env-subdomain> -> project ALB (project-tier; mod 038)
#
# Mod 044: gated on `reverse_proxy == "alb"`. EC2-traefik projects emit
# these five-host A-records at the project tier instead (the records all
# converge on the single traefik instance regardless of env).
# ---------------------------------------------------------------------------
resource "aws_route53_record" "env" {
  zone_id = data.terraform_remote_state.project.outputs.zone_id
  name    = "stage.docex-smoke-elastic.luxrnd.tech"
  type    = "A"
  alias {
    name                   = data.terraform_remote_state.project.outputs.alb_dns_name
    zone_id                = data.terraform_remote_state.project.outputs.alb_zone_id
    evaluate_target_health = false
  }
}

# Per-service subdomains (<service>.stage.docex-smoke-elastic.luxrnd.tech) all resolve to the
# same ALB; the listener rules dispatch by host header. One wildcard record
# covers every web service in this env.
resource "aws_route53_record" "env_wildcard" {
  zone_id = data.terraform_remote_state.project.outputs.zone_id
  name    = "*.stage.docex-smoke-elastic.luxrnd.tech"
  type    = "A"
  alias {
    name                   = data.terraform_remote_state.project.outputs.alb_dns_name
    zone_id                = data.terraform_remote_state.project.outputs.alb_zone_id
    evaluate_target_health = false
  }
}



