# Generated by `docex compile`. Do not edit by hand.
# project: docex_smoke_elastic v0.0.24
# tier: project (foundation: elastic)
# apex_domain: luxrnd.tech
#
# The resources here back every elastic environment's main.tf via
# `data "terraform_remote_state" "project"`. They are applied by
# `docex projinfra up production` against their own state file (project/terraform.tfstate)
# in the same S3 backend the bootstrap creates.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {
    bucket         = "docex-smoke-elastic-tofu-state"
    key            = "project/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "docex_smoke_elastic_tofu_locks"
    encrypt        = true
  }
}

provider "aws" {
  region = "us-east-1"
}

# ---------------------------------------------------------------------------
# Route53 hosted zone for the project subdomain (`<project>.<apex_domain>`).
#
# The zone covers the project's subdomain — not the bare apex. The apex zone
# typically belongs to whoever owns the registrar account; this project's
# zone is delegated from there via NS records.
#
# The operator must NS-delegate `<project>.<apex_domain>` from the parent
# zone (`<apex_domain>`, at the registrar or parent Route53 hosted zone)
# using the name servers printed by `docex projinfra up production` after the first apply.
# Until that delegation propagates, ACM DNS validation will not complete,
# which is why `docex projinfra up production` applies this zone first and pauses for
# delegation before proceeding to the certs.
# ---------------------------------------------------------------------------
resource "aws_route53_zone" "project" {
  name = "docex-smoke-elastic.luxrnd.tech"
  # WHY: the zone legitimately accrues records tofu doesn't own — dev A-records
  # that NS-delegation forces into the child zone (dev is fixed/out-of-band),
  # plus stale ACM validation CNAMEs. force_destroy sweeps all records on
  # `projinfra down production` so the zone delete can't hit HostedZoneNotEmpty.
  # See elastic_route53_zone.md § Teardown. Destroy-only; no effect on up.
  force_destroy = true
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "dns"
    descriptor = "zone"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_dns_zone"
  }
}

# ---------------------------------------------------------------------------
# Master VPC — preinfra. Operator brings it up out-of-band; docex consumes
# via tag-based data sources. See preinfra/elastic_master_network.md.
# ---------------------------------------------------------------------------
data "aws_vpc" "master" {
  # Mod 060: semantic tag filter (cicl.md § Naming and Tagging preinfra
  # block). Matches on the load-bearing identity tags, NOT the redundant
  # console-only `Name`. The master network is operator-managed preinfra,
  # so `managed_by=doctrine-operator`.
  tags = {
    managed_by = "doctrine-operator"
    infra_tier = "prerequisite"
    shape_name = "master_network"
  }
}

data "aws_subnets" "public" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.master.id]
  }
  tags = {
    tier = "public"
  }
}

data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.master.id]
  }
  tags = {
    tier = "private"
  }
}

# Primary-AZ private subnet — single-AZ commit per cicl.md.
data "aws_subnet" "primary_private" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.master.id]
  }
  filter {
    name   = "availability-zone"
    values = ["us-east-1a"]
  }
  tags = {
    tier = "private"
  }
}


# ---------------------------------------------------------------------------
# ACM certificates — one per ALB-served env.
#
# Two certs ship per project per the doctrine's "stage and prod cert-separated
# for blast-radius" rule (cicl.md § TLS Implications):
#   - Stage cert covers `*.stage.<project>.<apex>` and `stage.<project>.<apex>`.
#   - Prod cert covers `*.prod.<project>.<apex>`, `prod.<project>.<apex>`, and
#     the bare-project ergonomic `<project>.<apex>`.
# Dev and test envs are always fixed-style; they never reach the ALB and are
# excluded from these certs.
#
# Mod 044: ACM is ALB-only. EC2-traefik uses traefik's built-in Let's Encrypt
# client (DNS-01 via Route53) instead — see projinfra/ec2_traefik.md.
# ---------------------------------------------------------------------------
resource "aws_acm_certificate" "stage" {
  domain_name = "*.stage.docex-smoke-elastic.luxrnd.tech"
  subject_alternative_names = [
    "stage.docex-smoke-elastic.luxrnd.tech",
  ]
  validation_method = "DNS"
  lifecycle {
    create_before_destroy = true
  }
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "cert_manager"
    descriptor = "stage-cert"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_cert_manager_stage-cert"
  }
}

resource "aws_acm_certificate" "prod" {
  domain_name = "*.prod.docex-smoke-elastic.luxrnd.tech"
  subject_alternative_names = [
    "prod.docex-smoke-elastic.luxrnd.tech",
    "docex-smoke-elastic.luxrnd.tech",
  ]
  validation_method = "DNS"
  lifecycle {
    create_before_destroy = true
  }
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "cert_manager"
    descriptor = "prod-cert"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_cert_manager_prod-cert"
  }
}

resource "aws_route53_record" "cert_validation_stage" {
  for_each = {
    for dvo in aws_acm_certificate.stage.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.project.zone_id
}

resource "aws_route53_record" "cert_validation_prod" {
  for_each = {
    for dvo in aws_acm_certificate.prod.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.project.zone_id
}

resource "aws_acm_certificate_validation" "stage" {
  certificate_arn         = aws_acm_certificate.stage.arn
  validation_record_fqdns = [for record in aws_route53_record.cert_validation_stage : record.fqdn]
}

resource "aws_acm_certificate_validation" "prod" {
  certificate_arn         = aws_acm_certificate.prod.arn
  validation_record_fqdns = [for record in aws_route53_record.cert_validation_prod : record.fqdn]
}

# ---------------------------------------------------------------------------
# Project-tier ALB. One per project, serves stage and prod via SNI
# listener-cert bindings + env-tier listener rules. See
# projinfra/elastic_alb.md.
# ---------------------------------------------------------------------------
resource "aws_security_group" "project_alb" {
  name        = "docex-smoke-elastic-alb-sg"
  description = "Project ALB ingress (80/443 from internet); egress all."
  vpc_id      = data.aws_vpc.master.id
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "reverse_proxy"
    descriptor = "ALB-SG"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_reverse_proxy_ALB-SG"
  }
}

resource "aws_lb" "project" {
  name               = "docex-smoke-elastic-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.project_alb.id]
  subnets            = data.aws_subnets.public.ids
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "reverse_proxy"
    descriptor = "ALB"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_reverse_proxy_ALB"
  }
}

resource "aws_lb_listener" "project_https" {
  load_balancer_arn = aws_lb.project.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  # WHY: prod cert is the listener default; stage cert is attached as
  # an additional SNI binding below. SNI behavior selects whichever
  # cert's SAN matches the incoming Host header, and the default cert
  # is the conservative fallback for an unrecognised host.
  certificate_arn   = aws_acm_certificate_validation.prod.certificate_arn
  default_action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      status_code  = "404"
      message_body = "not found"
    }
  }
}

resource "aws_lb_listener_certificate" "project_stage" {
  listener_arn    = aws_lb_listener.project_https.arn
  certificate_arn = aws_acm_certificate_validation.stage.certificate_arn
}

resource "aws_lb_listener" "project_http" {
  load_balancer_arn = aws_lb.project.arn
  port              = 80
  protocol          = "HTTP"
  default_action {
    type = "redirect"
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }
}


# ---------------------------------------------------------------------------
# ECS clusters — one per elastic env (stage + prod), project-tier (mod 071).
#
# Both clusters always exist for every elastic project, on both reverse-proxy
# paths. WHY project-tier: the EC2-traefik ECS provider lists BOTH clusters
# statically; it treats a ListTasks error on any listed cluster as fatal for
# the entire refresh, so a stage-only release with the prod cluster absent
# would build zero routes. Empty ECS clusters are free. Each env's main.tf
# references its cluster ARN via terraform_remote_state (never creates one).
# ---------------------------------------------------------------------------
resource "aws_ecs_cluster" "stage" {
  name = "docex-smoke-elastic-stage"
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "ecs_cluster"
    descriptor = "stage"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_ecs_cluster_stage"
  }
}

resource "aws_ecs_cluster" "prod" {
  name = "docex-smoke-elastic-prod"
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "ecs_cluster"
    descriptor = "prod"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_ecs_cluster_prod"
  }
}

# ---------------------------------------------------------------------------
# ECR repositories — one per codebase. The image refs in each env's
# main.tf resolve to `<repo_url>:<version>`.
# ---------------------------------------------------------------------------

resource "aws_ecr_repository" "api" {
  name                 = "docex_smoke_elastic/api"
  image_tag_mutability = "MUTABLE"
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "container_registry"
    descriptor = "api"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_container_registry_api"
  }
}


# ---------------------------------------------------------------------------
# ECS task execution role.
#
# Fargate assumes this role *during launch* to pull images from ECR,
# fetch SSM parameters referenced in container `secrets[]` blocks, and
# write to CloudWatch Logs. Distinct from any "task role" the app
# itself might use to call AWS APIs at runtime — task role is per-app
# and out of scope for the doctrine skeleton.
#
# Provisioned at the project tier (not per-env) because the role's
# permissions are derived from project identity (the SSM prefix), not
# env identity. Each env's ECS task definitions reference the role ARN
# via terraform_remote_state.
# ---------------------------------------------------------------------------
data "aws_caller_identity" "current" {}

resource "aws_iam_role" "task_execution" {
  name = "docex_smoke_elastic_task_execution"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ecs-tasks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    managed_by = "doctrine"
    infra_tier = "project"
    shape_name = "etc"
    descriptor = "exec-role"
    project = "docex_smoke_elastic"
    Name = "docex_smoke_elastic_etc_exec-role"
  }
}

# Inline policy scoped to project resources only. Replaces the
# AWS-managed AmazonECSTaskExecutionRolePolicy with explicit grants so
# cross-project isolation is enforced at the IAM layer
# (projinfra/elastic_iam.md). KMS Decrypt is intentionally absent —
# AWS-managed `aws/ssm` key decryption requires no explicit grant.
resource "aws_iam_role_policy" "task_execution" {
  name = "docex_smoke_elastic_task_execution"
  role = aws_iam_role.task_execution.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "ecr:GetAuthorizationToken"
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "ecr:BatchCheckLayerAvailability",
          "ecr:BatchGetImage",
          "ecr:GetDownloadUrlForLayer",
        ]
        Resource = [
          aws_ecr_repository.api.arn,
        ]
      },
      {
        Effect   = "Allow"
        Action   = "ssm:GetParameters"
        Resource = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/stage/*"
      },
      {
        Effect   = "Allow"
        Action   = "ssm:GetParameters"
        Resource = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = [
          "arn:aws:logs:us-east-1:${data.aws_caller_identity.current.account_id}:log-group:/docex_smoke_elastic/stage/*",
          "arn:aws:logs:us-east-1:${data.aws_caller_identity.current.account_id}:log-group:/docex_smoke_elastic/prod/*",
        ]
      },
    ]
  })
}

# ---------------------------------------------------------------------------
# Outputs. Consumed by each env's main.tf via terraform_remote_state.
# ---------------------------------------------------------------------------
output "vpc_id" {
  value = data.aws_vpc.master.id
}

output "public_subnet_ids" {
  value = data.aws_subnets.public.ids
}

output "private_subnet_ids" {
  value = data.aws_subnets.private.ids
}

# Mod 041: primary-AZ private subnet for single-AZ ECS placement.
output "primary_private_subnet_id" {
  value = data.aws_subnet.primary_private.id
}

output "zone_id" {
  value = aws_route53_zone.project.zone_id
}

output "zone_name_servers" {
  value = aws_route53_zone.project.name_servers
}

output "task_execution_role_arn" {
  value = aws_iam_role.task_execution.arn
}

# Mod 071: project-tier ECS cluster ARNs, one per elastic env. Each env's
# main.tf references its own via `ecs_cluster_<env>_arn`.
output "ecs_cluster_stage_arn" {
  value = aws_ecs_cluster.stage.arn
}

output "ecs_cluster_prod_arn" {
  value = aws_ecs_cluster.prod.arn
}

# Mod 044: polymorphic output. Env-tier `web` SGs use it as their ingress
# source SG, regardless of which reverse-proxy variant the project picked.
output "reverse_proxy_security_group_id" {
  value = aws_security_group.project_alb.id
}


# ALB-only outputs. Gated on `reverse_proxy == "alb"` (mod 044) — projects
# using EC2-traefik don't have an ALB and these outputs would dangle.
output "stage_cert_arn" {
  value = aws_acm_certificate_validation.stage.certificate_arn
}

output "prod_cert_arn" {
  value = aws_acm_certificate_validation.prod.certificate_arn
}

output "alb_arn" {
  value = aws_lb.project.arn
}

output "alb_dns_name" {
  value = aws_lb.project.dns_name
}

output "alb_zone_id" {
  value = aws_lb.project.zone_id
}

output "alb_https_listener_arn" {
  value = aws_lb_listener.project_https.arn
}

output "alb_http_listener_arn" {
  value = aws_lb_listener.project_http.arn
}

output "alb_security_group_id" {
  value = aws_security_group.project_alb.id
}


output "ecr_repository_api_url" {
  value = aws_ecr_repository.api.repository_url
}

