# Generated by `docex compile`. Do not edit by hand.
# project: docex_smoke_elastic v0.0.8
# env: prod (foundation: elastic)
# domain: doctrine-elastic.luxrnd.tech -> www.doctrine-elastic.luxrnd.tech

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  # State backend reference (provisioned by `docex bootstrap`).
  backend "s3" {
    bucket         = "docex-smoke-elastic-tofu-state"
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "docex_smoke_elastic_tofu_locks"
    encrypt        = true
  }
}

provider "aws" {
  region = "us-east-1"
}

# AWS account ID — used downstream for SSM parameter ARNs in ECS
# secrets[] blocks. Resolved at apply time so `docex compile` stays
# offline-pure (no AWS creds required for compile).
data "aws_caller_identity" "current" {}

# ---------------------------------------------------------------------------
# Project-tier outputs (VPC, subnets, Route53 zone, ACM cert, ECR repos).
# Provisioned once by `docex bootstrap` against ../project/main.tf; the
# env-tier apply just composes them.
# ---------------------------------------------------------------------------
data "terraform_remote_state" "project" {
  backend = "s3"
  config = {
    bucket = "docex-smoke-elastic-tofu-state"
    key    = "project/terraform.tfstate"
    region = "us-east-1"
  }
}

# ---------------------------------------------------------------------------
# Network plane (security groups; one per CICL-declared network)
# ---------------------------------------------------------------------------
resource "aws_security_group" "internal" {
  name        = "docex_smoke_elastic_prod_internal"
  description = "internal network for docex_smoke_elastic prod"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  # WHY: aws_security_group denies egress when no egress block is given,
  # overriding AWS's allow-all default. Without this, Fargate tasks can't
  # reach SSM/ECR. Per-network egress restriction is deferred — see
  # infrastructure.md § Deferred rule 6.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    network    = "internal"
    managed_by = "doctrine"
  }
}

# Internal SG: accepts ingress only from itself (services in the same network).
resource "aws_security_group_rule" "internal_self_ingress" {
  type              = "ingress"
  from_port         = 0
  to_port           = 65535
  protocol          = "tcp"
  security_group_id = aws_security_group.internal.id
  self              = true
}

resource "aws_security_group" "web" {
  name        = "docex_smoke_elastic_prod_web"
  description = "web network for docex_smoke_elastic prod"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  # WHY: aws_security_group denies egress when no egress block is given,
  # overriding AWS's allow-all default. Without this, Fargate tasks can't
  # reach SSM/ECR. Per-network egress restriction is deferred — see
  # infrastructure.md § Deferred rule 6.
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    network    = "web"
    managed_by = "doctrine"
  }
}

# Web SG: open ingress only from the ALB SG.
resource "aws_security_group_rule" "web_ingress_from_alb" {
  type                     = "ingress"
  from_port                = 0
  to_port                  = 65535
  protocol                 = "tcp"
  security_group_id        = aws_security_group.web.id
  source_security_group_id = aws_security_group.alb.id
}



# ALB security group (allows public 443/80).
resource "aws_security_group" "alb" {
  name        = "docex_smoke_elastic_prod_alb"
  description = "ALB ingress for docex_smoke_elastic prod"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# Reverse proxy: one ALB per env
# ---------------------------------------------------------------------------
resource "aws_lb" "alb" {
  name               = "docex-smoke-elastic-prod-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = data.terraform_remote_state.project.outputs.public_subnet_ids
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    managed_by = "doctrine"
  }
}

resource "aws_lb_listener" "alb_https" {
  load_balancer_arn = aws_lb.alb.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  certificate_arn   = data.terraform_remote_state.project.outputs.certificate_arn
  default_action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      status_code  = "404"
      message_body = "not found"
    }
  }
}

resource "aws_lb_listener" "alb_http_redirect" {
  load_balancer_arn = aws_lb.alb.arn
  port              = 80
  protocol          = "HTTP"
  default_action {
    type = "redirect"
    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }
}

# ---------------------------------------------------------------------------
# ECS cluster
# ---------------------------------------------------------------------------
resource "aws_ecs_cluster" "cluster" {
  name = "docex_smoke_elastic_prod"
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# Service discovery — ECS Service Connect over a Cloud Map HTTP namespace.
# Per shape2.md § Elastic-Foundation, one namespace per env. Services
# register themselves via service_connect_configuration on aws_ecs_service.
# ---------------------------------------------------------------------------
resource "aws_service_discovery_http_namespace" "env" {
  name        = "docex_smoke_elastic_prod"
  description = "ECS Service Connect namespace for docex_smoke_elastic prod"
  tags = {
    project    = "docex_smoke_elastic"
    env        = "prod"
    managed_by = "doctrine"
  }
}

# ---------------------------------------------------------------------------
# Services (backing first, then core; dispatch is by engine.emits.elastic).
# Per Mod 013, both backing and core services flow through the same
# destination-driven renderer — what HCL gets emitted is governed by the
# engine's declared emit destinations.
# ---------------------------------------------------------------------------
data "aws_ssm_parameter" "appdb_postgres_user" {
  name            = "/docex_smoke_elastic/prod/POSTGRES_USER"
  with_decryption = true
}
data "aws_ssm_parameter" "appdb_postgres_password" {
  name            = "/docex_smoke_elastic/prod/POSTGRES_PASSWORD"
  with_decryption = true
}

resource "aws_db_instance" "appdb" {
  allocated_storage = 20
  backup_retention_period = 7
  db_name = "appdb"
  db_subnet_group_name = aws_db_subnet_group.appdb.name
  deletion_protection = true
  engine = "postgres"
  engine_version = "15"
  identifier = "docex-smoke-elastic-prod-appdb"
  instance_class = "db.t3.medium"
  password = data.aws_ssm_parameter.appdb_postgres_password.value
  publicly_accessible = false
  storage_encrypted = false
  storage_type = "gp3"
  tags = {
    env = "prod"
    managed_by = "doctrine"
    project = "docex_smoke_elastic"
    role = "relational_db"
    service = "appdb"
  }
  username = data.aws_ssm_parameter.appdb_postgres_user.value
  vpc_security_group_ids = [aws_security_group.internal.id]
}

resource "aws_db_subnet_group" "appdb" {
  name       = "docex-smoke-elastic-prod-appdb"
  subnet_ids = data.terraform_remote_state.project.outputs.private_subnet_ids
}


resource "aws_ecs_task_definition" "events" {
  family                   = "docex_smoke_elastic_prod_events"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "1024"
  memory                   = "4096"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  volume {
    name = "data"
    efs_volume_configuration {
      file_system_id     = aws_efs_file_system.events.id
      transit_encryption = "ENABLED"
    }
  }
  container_definitions = jsonencode([
    {
      essential = true
      image = "clickhouse/clickhouse-server:24.10"
      mountPoints = [{
          containerPath = "/var/lib/clickhouse"
          readOnly = false
          sourceVolume = "data"
        }]
      name = "events"
      portMappings = [{
          containerPort = 9000
          name = "events"
          protocol = "tcp"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "prod", service = "events", role = "analytics_db", managed_by = "doctrine" }
}

resource "aws_ecs_service" "events" {
  name            = "docex_smoke_elastic_prod_events"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.events.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = data.terraform_remote_state.project.outputs.private_subnet_ids
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_http_namespace.env.arn
    service {
      port_name      = "events"
      discovery_name = "docex_smoke_elastic_prod_events"
      client_alias {
        port     = 9000
        dns_name = "docex_smoke_elastic_prod_events"
      }
    }
  }
}

resource "aws_efs_file_system" "events" {
  creation_token   = "docex_smoke_elastic_prod_events"
  encrypted        = true
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  tags = { project = "docex_smoke_elastic", env = "prod", service = "events", role = "analytics_db", managed_by = "doctrine" }
}

resource "aws_efs_backup_policy" "events" {
  file_system_id = aws_efs_file_system.events.id
  backup_policy {
    status = "ENABLED"
  }
}

resource "aws_efs_mount_target" "events" {
  count           = length(data.terraform_remote_state.project.outputs.private_subnet_ids)
  file_system_id  = aws_efs_file_system.events.id
  subnet_id       = data.terraform_remote_state.project.outputs.private_subnet_ids[count.index]
  security_groups = [aws_security_group.internal.id]
}


resource "aws_ecs_task_definition" "probe" {
  family                   = "docex_smoke_elastic_prod_probe"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  container_definitions = jsonencode([
    {
      essential = true
      image = "nginx:1.27-alpine"
      name = "probe"
      portMappings = [{
          containerPort = 80
          name = "probe"
          protocol = "tcp"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "prod", service = "probe", role = "sidecar", managed_by = "doctrine" }
}

resource "aws_ecs_service" "probe" {
  name            = "docex_smoke_elastic_prod_probe"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.probe.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = data.terraform_remote_state.project.outputs.private_subnet_ids
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_http_namespace.env.arn
    service {
      port_name      = "probe"
      discovery_name = "docex_smoke_elastic_prod_probe"
      client_alias {
        port     = 80
        dns_name = "docex_smoke_elastic_prod_probe"
      }
    }
  }
}


resource "aws_ecs_task_definition" "web" {
  family                   = "docex_smoke_elastic_prod_web"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  ephemeral_storage {
    size_in_gib = 24
  }
  container_definitions = jsonencode([
    {
      dependsOn = [{
          condition = "START"
          containerName = "web_otelcol"
        }]
      environment = [{
          name = "CLICKHOUSE_HOST"
          value = "docex_smoke_elastic_prod_events"
        }, {
          name = "CLICKHOUSE_PORT"
          value = "9000"
        }, {
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.8,deployment.environment.name=prod"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "web"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.8"
        }, {
          name = "SIDECAR_HOST"
          value = "docex_smoke_elastic_prod_probe"
        }, {
          name = "SIDECAR_PORT"
          value = "80"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_web_url}:0.0.8"
      name = "web"
      portMappings = [{
          containerPort = 8080
          name = "web"
          protocol = "tcp"
        }]
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_USER"
        }]
    },
    {
      command = ["--config=env:OTEL_CONFIG_YAML"]
      cpu = 102
      environment = [{
          name = "OTEL_CONFIG_YAML"
          value = "# Generated by `docex compile`. Do not edit by hand.\n# env: prod\nreceivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 127.0.0.1:4318\nprocessors:\n  batch: {}\nexporters:\n  otlphttp:\n    endpoint: $${env:OBSERVABILITY_BACKEND_URL}\n    headers:\n      authorization: $${env:TELEMETRY_API_KEY}\nextensions:\n  health_check:\n    endpoint: 127.0.0.1:13133\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces:  { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    metrics: { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    logs:    { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n"
        }, {
          name = "OBSERVABILITY_BACKEND_URL"
          value = "https://hyperdx.luxrnd.tech"
        }]
      essential = false
      image = "otel/opentelemetry-collector:0.153.0@sha256:74edb825a429b415262e7eb7a99ed77685c9b2b7238ef69fb42a3625df75458f"
      memory = 128
      name = "web_otelcol"
      secrets = [{
          name = "TELEMETRY_API_KEY"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/TELEMETRY_API_KEY"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "prod", service = "web", role = "web", managed_by = "doctrine" }
}

resource "aws_ecs_task_definition" "web_migrate" {
  family                   = "docex_smoke_elastic_prod_web_migrate"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  container_definitions = jsonencode([
    {
      command = ["/service/migrate.sh"]
      environment = [{
          name = "CLICKHOUSE_HOST"
          value = "docex_smoke_elastic_prod_events"
        }, {
          name = "CLICKHOUSE_PORT"
          value = "9000"
        }, {
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.8,deployment.environment.name=prod"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "web"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.8"
        }, {
          name = "SIDECAR_HOST"
          value = "docex_smoke_elastic_prod_probe"
        }, {
          name = "SIDECAR_PORT"
          value = "80"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_web_url}:0.0.8"
      name = "web"
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_USER"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "prod", service = "web", role = "migrate", managed_by = "doctrine" }
}

resource "aws_ecs_service" "web" {
  name            = "docex_smoke_elastic_prod_web"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.web.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = data.terraform_remote_state.project.outputs.private_subnet_ids
    security_groups = [aws_security_group.internal.id, aws_security_group.web.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_http_namespace.env.arn
    service {
      port_name      = "web"
      discovery_name = "docex_smoke_elastic_prod_web"
      client_alias {
        port     = 8080
        dns_name = "docex_smoke_elastic_prod_web"
      }
    }
  }
  load_balancer {
    target_group_arn = aws_lb_target_group.web.arn
    container_name   = "web"
    container_port   = 8080
  }
}

resource "aws_lb_target_group" "web" {
  name        = "docex-smoke-elastic-prod-web-tg"
  port        = 8080
  protocol    = "HTTP"
  target_type = "ip"
  vpc_id      = data.terraform_remote_state.project.outputs.vpc_id
  health_check {
    path = "/health"
    healthy_threshold = 2
    unhealthy_threshold = 3
    interval = 30
    timeout = 5
  }
}

resource "aws_lb_listener_rule" "web" {
  listener_arn = aws_lb_listener.alb_https.arn
  priority     = 100
  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.web.arn
  }
  condition {
    host_header {
      values = ["www.doctrine-elastic.luxrnd.tech", "web.www.doctrine-elastic.luxrnd.tech"]
    }
  }
}


resource "aws_ecs_task_definition" "worker" {
  family                   = "docex_smoke_elastic_prod_worker"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = data.terraform_remote_state.project.outputs.task_execution_role_arn
  ephemeral_storage {
    size_in_gib = 24
  }
  container_definitions = jsonencode([
    {
      dependsOn = [{
          condition = "START"
          containerName = "worker_otelcol"
        }]
      environment = [{
          name = "DATABASE_HOST"
          value = "${aws_db_instance.appdb.address}"
        }, {
          name = "DATABASE_NAME"
          value = "appdb"
        }, {
          name = "DATABASE_PORT"
          value = "5432"
        }, {
          name = "DATABASE_SSLMODE"
          value = "require"
        }, {
          name = "OTEL_EXPORTER_OTLP_ENDPOINT"
          value = "http://localhost:4318"
        }, {
          name = "OTEL_EXPORTER_OTLP_PROTOCOL"
          value = "http/protobuf"
        }, {
          name = "OTEL_RESOURCE_ATTRIBUTES"
          value = "service.namespace=docex_smoke_elastic,service.version=0.0.8,deployment.environment.name=prod"
        }, {
          name = "OTEL_SERVICE_NAME"
          value = "worker"
        }, {
          name = "PROJECT_VERSION"
          value = "0.0.8"
        }]
      essential = true
      image = "${data.terraform_remote_state.project.outputs.ecr_repository_worker_url}:0.0.8"
      name = "worker"
      secrets = [{
          name = "DATABASE_PASSWORD"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_PASSWORD"
        }, {
          name = "DATABASE_USER"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/POSTGRES_USER"
        }]
    },
    {
      command = ["--config=env:OTEL_CONFIG_YAML"]
      cpu = 102
      environment = [{
          name = "OTEL_CONFIG_YAML"
          value = "# Generated by `docex compile`. Do not edit by hand.\n# env: prod\nreceivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 127.0.0.1:4318\nprocessors:\n  batch: {}\nexporters:\n  otlphttp:\n    endpoint: $${env:OBSERVABILITY_BACKEND_URL}\n    headers:\n      authorization: $${env:TELEMETRY_API_KEY}\nextensions:\n  health_check:\n    endpoint: 127.0.0.1:13133\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces:  { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    metrics: { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n    logs:    { receivers: [otlp], processors: [batch], exporters: [otlphttp] }\n"
        }, {
          name = "OBSERVABILITY_BACKEND_URL"
          value = "https://hyperdx.luxrnd.tech"
        }]
      essential = false
      image = "otel/opentelemetry-collector:0.153.0@sha256:74edb825a429b415262e7eb7a99ed77685c9b2b7238ef69fb42a3625df75458f"
      memory = 128
      name = "worker_otelcol"
      secrets = [{
          name = "TELEMETRY_API_KEY"
          valueFrom = "arn:aws:ssm:us-east-1:${data.aws_caller_identity.current.account_id}:parameter/docex_smoke_elastic/prod/TELEMETRY_API_KEY"
        }]
    },
  ])
  tags = { project = "docex_smoke_elastic", env = "prod", service = "worker", role = "web", managed_by = "doctrine" }
}

resource "aws_ecs_service" "worker" {
  name            = "docex_smoke_elastic_prod_worker"
  cluster         = aws_ecs_cluster.cluster.id
  task_definition = aws_ecs_task_definition.worker.arn
  launch_type     = "FARGATE"
  desired_count   = 1
  network_configuration {
    subnets         = data.terraform_remote_state.project.outputs.private_subnet_ids
    security_groups = [aws_security_group.internal.id]
  }
  service_connect_configuration {
    enabled   = true
    namespace = aws_service_discovery_http_namespace.env.arn
  }
}




# ---------------------------------------------------------------------------
# Route53 record: <env-subdomain> -> ALB
# ---------------------------------------------------------------------------
resource "aws_route53_record" "env" {
  zone_id = data.terraform_remote_state.project.outputs.zone_id
  name    = "www.doctrine-elastic.luxrnd.tech"
  type    = "A"
  alias {
    name                   = aws_lb.alb.dns_name
    zone_id                = aws_lb.alb.zone_id
    evaluate_target_health = false
  }
}

# Per-service subdomains (<service>.www.doctrine-elastic.luxrnd.tech) all resolve to the
# same ALB; the listener rules dispatch by host header. One wildcard record
# covers every web service in this env.
resource "aws_route53_record" "env_wildcard" {
  zone_id = data.terraform_remote_state.project.outputs.zone_id
  name    = "*.www.doctrine-elastic.luxrnd.tech"
  type    = "A"
  alias {
    name                   = aws_lb.alb.dns_name
    zone_id                = aws_lb.alb.zone_id
    evaluate_target_health = false
  }
}
