#!/usr/bin/env bash
# gen_resident.sh — Generate the resident-stratum `@`-include manifest.
#
# WHY THIS EXISTS: a SessionStart hook cannot inject the resident stratum — large
# hook output is capped to a ~2KB preview (and JSON additionalContext of that size
# is dropped entirely). The only uncapped eager-injection path is CLAUDE.md
# `@`-includes (memory files). So instead of a hook emitting the doctrine, this
# generator emits an `@`-include list that the memory chain loads:
#     CLAUDE.md -> @JEAN.md -> @RESIDENT.md -> @doctrine/*.md
#
# WHAT IT DOES (all idempotent — safe to run at setup AND on every SessionStart):
#   1. Scans $ROOT/doctrine for files whose leading frontmatter declares
#      `stratum: resident`, ordered shallowest-path-first.
#   2. Writes $ROOT/RESIDENT.md containing one `@./doctrine/...` line per resident
#      file. Written only when the content actually changes (no churn).
#
# It does NOT touch JEAN.md. JEAN.md carries a static, hand-maintained,
# git-tracked `@./RESIDENT.md` reference; setup never rewrites it.
#
# Membership stays frontmatter-driven; the manifest is fully derived, never
# hand-edited. stdout is intentionally empty so this is harmless if ever wired as
# a hook (nothing gets injected); all status goes to stderr.
set -eu

# Resolve the repo root from this script's own location ($ROOT/setup/claude/),
# so it works whether invoked by setup or by a plugin hook, with or without
# CLAUDE_PLUGIN_ROOT being set.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOCTRINE_DIR="$ROOT/doctrine"
MANIFEST="$ROOT/RESIDENT.md"

if [ ! -d "$DOCTRINE_DIR" ]; then
  echo "gen_resident: doctrine dir not found at $DOCTRINE_DIR" >&2
  exit 0
fi

# True iff the file's leading frontmatter block declares `stratum: resident`.
is_resident() {
  awk '
    NR==1 && $0 != "---" { exit }
    NR==1 { next }
    /^---[[:space:]]*$/ { exit }
    /^stratum:[[:space:]]*/ {
      v = $0; sub(/^stratum:[[:space:]]*/, "", v); gsub(/"/, "", v); sub(/[[:space:]]+$/, "", v)
      if (v == "resident") found = 1
      exit
    }
    END { exit(found ? 0 : 1) }
  ' "$1"
}

# Build the manifest body: a generated-file header (HTML comment) followed by one
# `@`-include per resident file, shallowest path first (ties broken by path).
build_manifest() {
  echo "<!-- GENERATED by setup/claude/gen_resident.sh from \`stratum: resident\` frontmatter. Do not edit by hand. -->"
  find "$DOCTRINE_DIR" -name '*.md' | while IFS= read -r f; do
    is_resident "$f" || continue
    depth=$(printf '%s' "$f" | tr -cd '/' | wc -c | tr -d ' ')
    printf '%s\t%s\n' "$depth" "$f"
  done | sort -t"$(printf '\t')" -k1,1n -k2,2 | cut -f2- | while IFS= read -r f; do
    printf '@./%s\n' "${f#"$ROOT"/}"   # path relative to repo root → @./doctrine/...
  done
}

new_content="$(build_manifest)"
count=$(printf '%s\n' "$new_content" | grep -c '^@\./' || true)

# Write the manifest only if it changed, to avoid mtime/git churn on no-op runs.
if [ -f "$MANIFEST" ] && [ "$(cat "$MANIFEST")" = "$new_content" ]; then
  echo "gen_resident: manifest unchanged ($count resident files)" >&2
else
  printf '%s\n' "$new_content" > "$MANIFEST"
  echo "gen_resident: wrote $MANIFEST ($count resident files)" >&2
fi
